from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime, timezone


class ImpactLevel(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class FollowUpRecommendation(BaseModel):
    title: str = Field(..., description="Follow-up task title")
    description: str = Field(..., description="Action items for property continuity")
    due_in_days: int = Field(..., ge=1, description="Target execution window in days")
    continuity_category: str = Field(..., description="Post-Repair Warranty, Preventive, Structural Recheck")
    assigned_role: str = Field(default="Representative")


class ApprovalProposal(BaseModel):
    """
    Structured output generated by ValidationContinuityAgent.
    Flags high-impact actions and prepares formal human approval request without executing it.
    """
    workflow_instance_id: str
    impact_level: ImpactLevel
    requires_human_approval: bool = True
    authorized_roles: List[str] = Field(default_factory=lambda: ["Manager", "Admin"])
    action_type: str = Field(..., description="e.g. ApproveQuotation, AuthorizeJobExecution")
    requested_amount_lkr: Optional[float] = None
    summary_for_approver: str = Field(..., description="Concise briefing for the Manager/Admin")
    risk_factors: List[str] = Field(default_factory=list)
    recommended_follow_ups: List[FollowUpRecommendation] = Field(default_factory=list)
    created_at_utc: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
