from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime, timezone


class PriorityLevel(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class StepProposal(BaseModel):
    step_order: int = Field(..., ge=1, description="Sequential order of the step")
    step_name: str = Field(..., description="Short title of the step")
    action_description: str = Field(..., description="Clear explanation of the action to execute")
    assigned_role: str = Field(..., description="Role responsible (Representative, ServiceProvider, Manager)")
    estimated_duration_hours: float = Field(..., gt=0, description="Estimated duration in hours")
    requires_approval: bool = Field(default=False, description="Whether this step requires human approval")


class RiskAssessment(BaseModel):
    structural_risk: str = Field(..., description="Assessment of structural degradation risk")
    financial_risk: str = Field(..., description="Risk of budget overrun or unquoted costs")
    urgency_rationale: str = Field(..., description="Explanation of why this priority level was assigned")


class WorkflowPlan(BaseModel):
    """
    Structured output generated by the IncidentPlanningAgent.
    """
    plan_id: str = Field(..., description="Unique plan identifier")
    workflow_instance_id: str = Field(..., description="Target WorkflowInstance GUID")
    incident_category: str = Field(..., description="Classified incident category (e.g., Plumbing, Roofing)")
    assessed_priority: PriorityLevel = Field(..., description="Assessed priority level")
    estimated_cost_range_lkr: str = Field(..., description="Estimated cost bracket in LKR (e.g., '25,000 - 45,000')")
    risk_assessment: RiskAssessment
    steps: List[StepProposal] = Field(default_factory=list, description="Ordered steps required for resolution")
    created_at_utc: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
