from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime, timezone


class ProviderCandidate(BaseModel):
    provider_id: str = Field(..., description="ServiceProvider GUID")
    business_name: str = Field(..., description="Provider business or trade name")
    distance_km: float = Field(..., ge=0, description="Haversine distance from asset in km")
    matching_score: float = Field(..., ge=0, le=100, description="Overall matching score (0-100)")
    score_breakdown: str = Field(..., description="Explainable breakdown of score")
    verification_status: str = Field(..., description="Verified, Pending, etc.")
    is_recommended: bool = Field(default=False)


class ProviderMatchProposal(BaseModel):
    """
    Structured output generated by the ProviderIntelligenceAgent.
    """
    workflow_instance_id: str
    incident_category: str
    asset_city: str
    candidates_evaluated: int
    ranked_candidates: List[ProviderCandidate]
    recommended_provider_id: Optional[str] = None
    selection_reasoning: str = Field(..., description="Factual justification for top recommendation")
    created_at_utc: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class QuotationAnalysis(BaseModel):
    quotation_id: str
    provider_name: str
    total_amount_lkr: float
    is_within_budget: bool
    budget_variance_percentage: float
    item_count: int
    has_labor_breakdown: bool
    warranty_months: int
    audit_notes: List[str] = Field(default_factory=list)


class MaintenanceRecommendation(BaseModel):
    """
    Structured output generated by the CostRecommendationAgent.
    """
    workflow_instance_id: str
    estimated_budget_lkr: float
    inspections_analyzed: int
    quotations_compared: int
    quotation_analyses: List[QuotationAnalysis] = Field(default_factory=list)
    recommended_quotation_id: Optional[str] = None
    recommended_amount_lkr: Optional[float] = None
    cost_saving_summary: str
    warranty_assurance_summary: str
    recommendation_summary: str = Field(..., description="Evidence-backed cost/quality tradeoff rationale")
    created_at_utc: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
